### ISSUE TITLE
using `polygons` directly limits flexibility

### ISSUE THREAD

**Issue by raybellis** [benjaminwand/_extrude#2]
There are parameters to the `polygons` function that this API does not expose.   I would suggest that instead you just use `children()` and then let the caller use whatever polygon options they like, or indeed use 2D primitives such as `circle()`.

You may also wish to expose the other parameters to `linear_extrude`, e.g.

    module xz_extrude(height, center, convexity, twist, slices, scale, $fn) {
        rotate([90, 0, 0]) mirror([0, 0, 1])
        linear_extrude(height = height, center = center, convexity = convexity, twist = twist, slices = slices, scale = scale, $fn = $fn)
        children();
    };

with example usage:

    xz_extrude(height = 3, scale = 0.6) circle(3, $fn = 24);

**Comment by benjaminwand** [comment]
You are totally right but for what I've programmed/created/designed so far I only had the pain to want to extrude on other planes with polygons.

**Comment by raybellis** [comment]
Sure, but you did say:

> If people have ideas how to develop it further I'd be happy to hear about it

:)

The `children()` method is one of the incredible strengths of the OpenSCAD language - it allows the introduction of new modules that _compose_ with other modules, instead of ones that just act as "leaf nodes" in the CSG hierarchy.

**Comment by benjaminwand** [comment]
OK, fine. Can it be done in a way that it is more versatile but still not more complicated to use for me, for instance by making polygons the default?

**Comment by raybellis** [comment]
You could provide two versions, e.g. `xy_extrude` and `xy_extrude_poly`.   I'll submit a PR.

**Comment by benjaminwand** [comment]
Thanks!

**Comment by raybellis** [comment]
closed by #3
